server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心创建的动态路由功能，利用微服务名进行路由
      routes:
        - id: payment-routh     #路由的ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri:  lb://CLOUD-PROVIDER-SERVICE  #lb代表从注册中心获取服务
          predicates:
            - Path=/payment/get/**   #断言，路径相匹配的进行路由匹配

        - id: payment-routh2     #路由的ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri:  lb://CLOUD-PROVIDER-SERVICE #匹配后提供服务的路由地址
          predicates:
              - Path=/payment/lb/**   #断言，路径相匹配的进行路由匹配
              #            - After=2021-03-23T21:45:50.741+08:00[Asia/Shanghai]
              #            - Cookie=username,sss
              #            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式
#              - Host=**.play.com
#              - Method=GET
#              - Query=username,\d+
eureka:
  instance:
    hostname: cloud-gateway-service  #eureka本机实例名称
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
